# Generated by Django 4.1.5 on 2023-01-31 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alabanza', '0002_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='musicians',
        ),
        migrations.CreateModel(
            name='ScheduleMusicianInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alabanza.instrument')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alabanza.musician')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musicians', to='alabanza.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'musician', 'instrument')},
            },
        ),
    ]
